name: rocket_chat_dart_sdk
description: A starting point for Dart libraries or applications.
version: 0.0.2
homepage: https://github.com/grahamsmith/Rocket-Chat-Dart-SDK

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: ^1.6.0
  retrofit: ^1.3.4
  logger: any
  dio: ^3.0.1
  json_serializable: ^3.3.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.14.6
  retrofit_generator: ^1.3.7
  build_runner: any
