name: rocket_chat_dart_sdk
description: A starting point for Dart libraries or applications.
version: 0.0.2
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: ^1.6.0
  retrofit: any
  logger: any
  dio: ^3.0.1
  json_serializable: any

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  retrofit_generator: any
  build_runner: any
